#language: c
sudo: required

services:
  - docker

git:
  depth: false

env:
  global:
    - secure: "V6Fww6hQLaoajQmJnS8cyUAv7AEEwtrJDXkZC08/CRs10PoozP0idzgYCk3aHM0l2BiN/dvZCb9rNL9ZLv9LYmnZCvQ/OVOC6vFZHWebcd0wf3RWAPZzRsAXrFtRxDu9JbzJcQsW95c+9rKrtiiFSIQHUni1CYEbmFx4J7hB3Fl5Hb60wMbP5aanS9LP2X0f5Rl7idkXXxxY/3eFg4ZZWIODlCnuiYNuyuU26iR5I9VsL6+bu77aFZJ85z1ywvVvqV3ZIY0rr2EWQPtg4gilAnnkFjPDGz6vYIATuMPHflK/M+gcvLJqt0B/s8wMPX2mtNWJ191um2JoYBgZh6dykg89YUIsR4DFcLGTLRyK5X/6iLiBbkl7UwKU4/UDdiKt6mnh9KG8kM5c6U9QXUglvfoA7x4KlLNRPohqbxZskw5OTnf30zMKiDSL0buCA8Y1m5PBAdqR53/ruyxDZLgGd2Qv0lTktBxYYD04PBUbrW7SSxbTkzOudvXrXbGc0B2YhJnMTl3qkUSiXcxKyrROKdhMKL+Wg96YRnkJ01eMfqK9w56iAMfe3TIl+jFnvLLUFZlKC6jClW1tb9eRs+gxW6OLuDl44ReZ6q9qJhOXAIXXsJ3uon7ZT86hyQ8C8t4rteUUEXfCT/+lPtqmlD3WmkZ3abpHhlBIY9/GfqoNoyM="

stages:
  - stable package
  - nightly package

# by default stage=test
# matrix only works for top level script
#script:
#  - bundle install --jobs=3 --retry=3 --deployment
#  - RAILS_ENV=test bundle exec rake db:create db:structure:load db:migrate
#  - RAILS_ENV=test bundle exec rake db:second_base:create db:second_base:structure:load db:second_base:migrate
#  - RAILS_ENV=test bundle exec rake db:seed
#  - bundle exec parallel_test spec/ -n $TEST_GROUPS_QTY --only-group $TEST_GROUP --group-by filesize --type rspec
#  - echo "Slowest spec files for TEST_GROUP $TEST_GROUP from $TEST_GROUPS_QTY"
#  - script/format_runtime_log log/parallel_runtime_rspec.log

jobs:
  include:
    - stage: stable package
      if: branch != master OR tag =~ ^.*$
      env: CACHE_NAME=stretch_package
      name: Stable Stretch Package
      script: &build_stretch
        - docker build -t yeti-lb -f ./ci/build_stretch.Dockerfile .
        - docker run --name yeti-lb yeti-lb && docker commit yeti-lb yeti-lb:built
      deploy:
        skip_cleanup: true
        provider: script
        script: docker run --name yeti-lb-deploy yeti-lb:built ci/deploy.sh "$API_ENDPOINT" stretch "${TRAVIS_TAG:0:3}" main /build/*.deb
        on:
          tags: true
          condition: "$TRAVIS_TAG != *-master*"
          repo: yeti-switch/yeti-lb

    - stage: nightly package
      if: branch = master
      env: CACHE_NAME=stretch_package
      name: Nightly Stretch Package
      script: *build_stretch
      deploy:
        skip_cleanup: true
        provider: script
        script: docker run --name yeti-lb-deploy yeti-lb:built ci/deploy.sh "$API_ENDPOINT" stretch nightly main /build/*.deb
        on:
          all_branches: true
          repo: yeti-switch/yeti-lb

